#!/usr/bin/env python3
"""
SFA v4 Image Generation Workflow Test
Test the orchestrator's ability to create multi-modal workflows with DALL-E 3
"""

import asyncio
import json
from orchestrator.core import WorkflowOrchestrator
from orchestrator.model_manager import UniversalModelManager

async def test_logo_design_workflow():
    """Test: Create a comprehensive logo design strategy with image generation"""
    
    # Initialize the orchestrator
    orchestrator = WorkflowOrchestrator("configs")
    
    # Test natural language goal
    user_goal = """Create a complete logo design strategy for a sustainable tech startup called 'EcoFlow'. 
    Include market research, design concepts, and generate 3 actual logo variations using AI."""
    
    print("🎨 SFA v4 IMAGE GENERATION WORKFLOW TEST")
    print("=" * 60)
    print(f"Goal: {user_goal}")
    print("=" * 60)
    
    try:
        # Create workflow from natural language
        print("\n🧠 ORCHESTRATOR: Analyzing goal and creating workflow...")
        workflow = await orchestrator.create_workflow_from_goal(user_goal)
        
        print(f"\n📋 WORKFLOW CREATED:")
        print(f"Name: {workflow.name}")
        print(f"Phases: {len(workflow.phases)} phases")
        
        # Show workflow structure
        for phase in workflow.phases:
            print(f"\n  🔸 {phase.name.replace('_', ' ').title()}")
            print(f"    Model: {phase.model}")
            print(f"    Agent: {phase.agent_role}")
            print(f"    Outputs: {', '.join(phase.output_files)}")
        
        # Use workflow's estimated cost
        print(f"\n💰 ESTIMATED COST: ${workflow.total_estimated_cost:.3f}")
        
        # Execute workflow
        print(f"\n🚀 EXECUTING WORKFLOW...")
        print("=" * 60)
        
        results = await orchestrator.execute_workflow(workflow.id)
        
        # Show results
        print(f"\n✅ WORKFLOW COMPLETE!")
        print(f"Total phases: {len(workflow.phases)}")
        print(f"Successful phases: {len([r for r in results['results'] if r['success']])}")
        print(f"Final cost: ${results['total_cost']:.3f}")
        
        # Show deliverables
        print(f"\n📁 DELIVERABLES:")
        for phase in workflow.phases:
            for output_file in phase.output_files:
                print(f"  ✓ {output_file}")
        
        # Show any image generation phases
        image_phases = [p for p in workflow.phases if 'image' in p.name.lower()]
        if image_phases:
            print(f"\n🖼️  IMAGE GENERATION PHASES:")
            for phase in image_phases:
                print(f"  🎨 {phase.name} using {phase.model}")
                for output in phase.output_files:
                    print(f"      → {output}")
        
        return True
        
    except Exception as e:
        print(f"\n❌ ERROR: {e}")
        return False

async def test_simple_image_generation():
    """Test: Simple direct image generation"""
    
    orchestrator = WorkflowOrchestrator("configs")
    
    print("\n" + "=" * 60)
    print("🎨 SIMPLE IMAGE GENERATION TEST")
    print("=" * 60)
    
    # Simple image generation goal
    goal = "Generate a minimalist logo for a coffee shop called 'Bean There'"
    
    print(f"Goal: {goal}")
    
    try:
        # This should create a single-phase workflow with DALL-E 3
        workflow = await orchestrator.create_workflow_from_goal(goal)
        
        print(f"\n📋 WORKFLOW: {workflow.name}")
        
        # Execute
        results = await orchestrator.execute_workflow(workflow.id)
        
        print(f"\n✅ RESULT: ${results['total_cost']:.3f}")
        # Show image generation phases
        image_phases = [p for p in workflow.phases if 'image' in p.name.lower()]
        if image_phases:
            for phase in image_phases:
                print(f"🎨 Generated by: {phase.model}")
        
        return True
        
    except Exception as e:
        print(f"\n❌ ERROR: {e}")
        return False

async def test_mixed_workflow():
    """Test: Mixed text + image workflow to stress test the orchestrator"""
    
    orchestrator = WorkflowOrchestrator("configs")
    
    print("\n" + "=" * 60)
    print("🔀 MIXED WORKFLOW TEST")
    print("=" * 60)
    
    goal = """Research the top 3 competitors in sustainable packaging, analyze their marketing strategies, 
    create a competitive positioning strategy, and generate marketing visuals for our eco-friendly 
    packaging startup 'GreenWrap'."""
    
    print(f"Goal: {goal}")
    
    try:
        workflow = await orchestrator.create_workflow_from_goal(goal)
        
        print(f"\n📋 WORKFLOW: {workflow.name}")
        print(f"Phases: {len(workflow.phases)}")
        
        # Show model selection across phases
        models_used = []
        for phase in workflow.phases:
            model = phase.model
            models_used.append(model)
            print(f"  {phase.name}: {model}")
        
        # Should show smart model selection:
        # Research → Gemini (free, huge context)
        # Analysis → Claude (reasoning)
        # Image Generation → DALL-E 3
        
        print(f"\n🤖 MODELS SELECTED: {len(set(models_used))} different models")
        for model in set(models_used):
            count = models_used.count(model)
            print(f"  {model}: {count} phase{'s' if count > 1 else ''}")
        
        # Use workflow's estimated cost
        print(f"\n💰 ESTIMATED COST: ${workflow.total_estimated_cost:.3f}")
        
        return True
        
    except Exception as e:
        print(f"\n❌ ERROR: {e}")
        return False

async def main():
    """Run all image generation tests"""
    
    print("🚀 SFA v4 IMAGE GENERATION TESTING SUITE")
    print("Testing the revolutionary orchestrator + image generation capabilities!")
    print("=" * 80)
    
    tests = [
        ("Logo Design Strategy", test_logo_design_workflow),
        ("Simple Image Generation", test_simple_image_generation), 
        ("Mixed Text + Image Workflow", test_mixed_workflow)
    ]
    
    results = []
    
    for test_name, test_func in tests:
        print(f"\n🧪 RUNNING TEST: {test_name}")
        success = await test_func()
        results.append((test_name, success))
    
    # Summary
    print("\n" + "=" * 80)
    print("🎯 TEST RESULTS SUMMARY")
    print("=" * 80)
    
    passed = sum(1 for _, success in results if success)
    total = len(results)
    
    for test_name, success in results:
        status = "✅ PASS" if success else "❌ FAIL"
        print(f"{status}: {test_name}")
    
    print(f"\n🏆 OVERALL: {passed}/{total} tests passed")
    
    if passed == total:
        print("\n🎉 ALL TESTS PASSED! Image generation workflows are WORKING! 🎨💎")
    else:
        print(f"\n⚠️  {total - passed} test(s) failed - need debugging")

if __name__ == "__main__":
    asyncio.run(main())
