#!/bin/bash
# Setup script to make 'mao' command available globally
# This creates the command that allows 'mao mao' to launch the beautiful terminal UI

echo "🚀 Setting up Mao command..."

# Get the absolute path to the project directory (go up one level from scripts/)
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LAUNCHER_PATH="$PROJECT_DIR/mao_v4.py"

# Create the mao command script
cat > /usr/local/bin/mao << EOF
#!/bin/bash
# Mao Terminal Interface Command
# Generated by setup_mao_command.sh

# Check if Python 3 is available
if ! command -v python3 &> /dev/null; then
    echo "❌ Python 3 is required but not installed"
    exit 1
fi

# Launch MAO with all arguments passed through
python3 "$LAUNCHER_PATH" "\$@"
EOF

# Make the command executable
chmod +x /usr/local/bin/mao

# Verify the command works
if command -v mao &> /dev/null; then
    echo "✅ MAO command installed successfully!"
    echo ""
    echo "🎭 You can now use:"
    echo "   mao mao          # Launch beautiful terminal UI"
    echo "   mao --login      # Force login screen"
    echo "   mao --continue   # Continue last session"
    echo "   mao --config     # Open configuration"
    echo "   mao --help       # See all options"
    echo ""
    echo "🚀 Try running: mao mao"
else
    echo "❌ Failed to install MAO command"
    echo "💡 You may need to run this script with sudo:"
    echo "   sudo bash setup_mao_command.sh"
    exit 1
fi