#!/bin/bash
# Install script for the Mao terminal interface command

# Set paths
BIN_DIR="${HOME}/bin"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

# Create bin directory if it doesn't exist
mkdir -p "$BIN_DIR"

# Backup existing mao if it exists
if [ -f "${BIN_DIR}/mao" ]; then
    echo "Backing up existing mao to mao.backup..."
    cp "${BIN_DIR}/mao" "${BIN_DIR}/mao.backup"
fi

# Create the mao command in bin directory (NO .sh extension)
echo "🚀 Creating Mao command in ${BIN_DIR}..."
cat > "${BIN_DIR}/mao" << EOF
#!/bin/bash
# Mao Terminal Interface Command
# Generated by install_mao_command.sh

# Get the absolute path to the project directory
PROJECT_DIR="$PROJECT_DIR"
LAUNCHER_PATH="\$PROJECT_DIR/mao_v4.py"

# Check if Python 3 is available
if ! command -v python3 &> /dev/null; then
    echo "❌ Python 3 is required but not installed"
    exit 1
fi

# Launch Mao with all arguments passed through
python3 "\$LAUNCHER_PATH" "\$@"
EOF

# Make the command executable
chmod +x "${BIN_DIR}/mao"

# Check if ~/bin is in PATH
if [[ ":$PATH:" != *":$HOME/bin:"* ]]; then
    echo "⚠️  ~/bin is not in your PATH"
    echo "💡 Add this to your shell profile (~/.bashrc, ~/.zshrc, etc.):"
    echo "   export PATH=\"\$HOME/bin:\$PATH\""
    echo ""
fi

# Verify the command was created
if [ -f "${BIN_DIR}/mao" ]; then
    echo "✅ Mao command installed successfully!"
    echo ""
    echo "🎭 You can now use:"
    echo "   mao           # New user onboarding"
    echo "   mao mao       # Smart launch (git-inspired)"
    echo ""
    echo "🚀 Try running: mao mao"
    echo ""
    echo "📝 Note: Make sure ~/bin is in your PATH to use 'mao' directly"
else
    echo "❌ Failed to create Mao command"
    exit 1
fi